apiVersion: v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: pingintelligence/ui-image:latest
        ports:
        - containerPort: 3000


---

apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30030
      targetPort: 3000
  #clusterIP: 10.0.171.239
  type: LoadBalancer
# status:
#   loadBalancer:
#     ingress:
#     - ip: 192.0.2.127