apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: user-mgmt
  name: user-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-mgmt
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: user-mgmt
    spec:
      containers:
        - image: pingintelligence/user-mgmt-image:latest
          name: user-mgmt
          ports:
            - containerPort: 8091
          resources: {}
      restartPolicy: Always
status: {}
